### ISSUE TITLE
Suggestion: Don't change `system` partition

### ISSUE THREAD

**Issue by farooqkz** [AshiVered/SkyOS#3]
Playing with `system` partition is not safe. I suggest distributing image file for `data`. In the case something goes wrong a factory reset will bring the phone back alive.

**Comment by AshiVered** [comment]
A. Not all changes can be made with` data`.
B. You can flash back the original `system`.

**Comment by farooqkz** [comment]
What changes need the `system` partition to be changed?

**Comment by AshiVered** [comment]
build.prop changes, ad blocking, init.d changes, etc.
